FriendsOfPHP/Sami

- Sami/Resources/themes/default/css/sami.css
The api tree in the left column of the default theme has a CSS height of `100%`. Because of the search form and version switcher at the top of the left column, the api tree is too high and can't be scrolled completely down, leaving the items displayed at the bottom invisible. Take the [Laravel API](http://laravel.com/api/5.0/index.html) for example:
I fixed the issue using a CSS flexbox while remaining fully compatible to browsers not supporting flexbox (those have to live with the invisible items).
See the fix applied to the example from above:
> Fixes a bug with the height of the api-tree in the default theme

- Sami/Renderer/ThemeSet.php
This PR closes #160 to ensure that Sami parses the contents of a yaml file rather than trying to parse the filename of a yaml file.
> Adding a fix to parse the contents of a file rather than trying to parse a filename

- Sami/Parser/NodeVisitor.php
I've downloaded a fresh copy of Sami to document my code. However when I tried to generate the documentation I encountered the error below.
[ErrorException]
Notice: Undefined property: PhpParser\Node\Stmt\Interface_::$type in ~/sami/vendor/sami/sami/Sami/Parser/NodeVisitor.php line 114
When I made the changes indicated in this request, I was able to generate my documentation. Was this a bug? Or have I an issue with my installation?
> Undefined Property

- README.rst
- Sami/Parser/ClassVisitor/ViewSourceClassVisitor.php
- Sami/Parser/Parser.php
- Sami/Project.php
- Sami/Reflection/ClassReflection.php
- Sami/RemoteRepository/AbstractRemoteRepository.php
- Sami/RemoteRepository/GitHubRemoteRepository.php
- Sami/Resources/themes/default/class.twig
- Sami/Resources/themes/default/macros.twig
- Sami/Sami.php
This is an implementation of #63 task based on original commit made in #64.
___Usage___
By default Sami doesn't know on which hosting Git repository is located and doesn't add `View Source` links on class detail pages. However if you specify `remote_repository` option with instance of `AbstractRemoteRepository` class sub-class, then the `View Source` link would be added:
For example:
```php
array(
...
'remote_repository' => new GitHubRemoteRepository('username/repository', '/path/to/repository'),
...
)
```
The `'/path/to/repository'` is required, because Sami doesn't know base folder on GitHub (or any other service), where original files (for which documentation is being generated) live.
Thanks to @anlutro, which commit (squashed) was used as a base for my changes.
Closes #63
> Adding "View Source" link to the class page

- Sami/Resources/themes/default/layout/base.twig
Without these tags the responsive works on desktop but not on mobile. I only tested this on an S5 but I presume other devices would have similar issues.
> Add responsive meta tags.

- Sami/Parser/ClassTraverser.php
- Sami/Parser/ClassVisitor/InheritdocClassVisitor.php
- Sami/Parser/ClassVisitor/ViewSourceClassVisitor.php
- Sami/Parser/Parser.php
- Sami/Reflection/ClassReflection.php
- Sami/Sami.php
While fixing some bugs on Sami, I spent some time measuring Sami speed with Blackfire. For now, I've just analyzed the parsing phase, and this is the first optimization pass based on what I've seen on Blackfire.
I can see a 25/30% speed improvement over Twig or Symfony when cache is there:
https://blackfire.io/profiles/compare/d8aa0168-ed7a-4721-8695-cd86b051b6c7/graph
and a negligible impact when cache is not available:
https://blackfire.io/profiles/compare/1a4d0266-60fb-4c4e-abd4-576ea0f76d51/graph
The speed-up comes from:
* Not storing the same class more than once;
* Not visiting classes when they come from the cache are were not modified (or their parent/interfaces).
> Improve parsing speed when cache is available

- Sami/Reflection/MethodReflection.php
- Sami/Resources/themes/default/class.twig
- Sami/Resources/themes/default/macros.twig
The link will be shown as the "at line ###" part for each method.
Using the link, the users can directly jump to the method source.
This is an extension of #91
> Add a link to class methods if a remote repository is configured

- Sami/Parser/NodeVisitor.php
A `PhpParser\Node\Name\FullyQualified` parsed parameter type is not handle like it must be. The `resolveAlias` method check for the `\\` prefix which is missing here so we got a wrong alias.
Now, the parameter parsed type is checked to add the prefix when necessary.
Work on #194
> Handle FQCN parsed parameter as it

- Sami/Parser/ClassVisitor/PropertyClassVisitor.php
- Sami/Parser/DocBlockParser.php
- Sami/Sami.php
The built-in code for parsing `@property` tag is now replaced with call to phpDocumentor class (we use it already in other places) to have consistent parsing.
Closes #205
> Use phpDocumentor's parser for "@property" tag parsing

- Sami/Parser/ClassVisitor/PropertyClassVisitor.php
- Sami/Tests/Parser/ClassVisitor/PropertyClassVisitorTest.php
Fixing failing `PropertyClassVisitorTest`, that was broken since #206.
> Fixing failing "PropertyClassVisitor" class test

- Sami/Resources/themes/default/class.twig
The `method_source_link` macro already returns `line X` or `<a href="...">line X</a>` and adding one more `line` word in front of it's result is redundant.
> The "line" word was shown twice in method line link

- Sami/Console/Command/ParseCommand.php
Before PR:
```php vendor/bin/sami.php parse parse config/symfony.php --force```
...
After PR:
```php vendor/bin/sami.php parse config/symfony.php --force```
...
> Fix help messages for update and render commands

- .travis.yml
- CHANGELOG
- Sami/Sami.php
- Sami/Tests/IntegrationTest.php
- composer.json
- composer.lock
Upgrading to Symfony 3.0 means : 
* removal of 5.3 and 5.4 support;
* bumping to a new major version.
As we have a new major version, I have also:
* removed support for Twig 1.x;
* upgraded to PHPParser version 3.0.
Fixes #232, #192, #217, #216, and #228
> upgraded to Symfony 3.0

- Sami/Resources/themes/default/class.twig
- Sami/Resources/themes/default/css/sami.css
- Sami/Resources/themes/default/macros.twig
Remove css ::before selector and add li elements with backslashes to make
the breadcrumb copyable.
> feature #283 Make namespace copyable

- Sami/Version/VersionCollection.php
This change fixes the Sami for PHP 7.2
Otherwise it fails on PHP 7.2:
> count(): Parameter must be an array or an object that implements Countable
> Fix Sami for PHP 7.2

- Sami/Parser/NodeVisitor.php
As discussed on issues #294 and #252, there's a bug in Sami that prevents it generating documentations when it reaches anonymous classes nodes - a feature from PHP 7.x.
As it was never supported before and I'm not sure if it's reasonable to have support for that I'm just proposing this PR to skip those anonymous classes and let Sami works flawlessly as before.
> Make Sami skip anonymous classes (fixes #294 and #252)

- Sami/Console/Command/Command.php
Before this change it's possible to define the "input" variable in the config file and have it pollute the scope of the loading block. After this change scope is completely isolated.
> Prevent scope collision in sami config file

- Sami/Project.php
- Sami/Renderer/Renderer.php
- Sami/Tests/ProjectTest.php
Fixes #62 (four year old bug :) )
I appreciate critique regarding the removal of the cache warming between versions; My experience is that the error in the output outweigh the performance benefit, but I stand to be corrected if possible. :)
Possibly there is another caching warming / reuse pattern that could be replaced, but I'm not familiar enough with the design to implement one I'm afraid.
I had some issue with ArrayStore not respecting the project version, but out of respect I've opted not to try to shiv in a fix for it.
> BUG Correct cache pollution between versions

- Sami/Tests/IntegrationTest.php
- Sami/Tests/Parser/ClassTraverserTest.php
- Sami/Tests/Parser/ClassVisitor/MethodClassVisitorTest.php
- Sami/Tests/Parser/ClassVisitor/PropertyClassVisitorTest.php
- Sami/Tests/Parser/DocBlockParserTest.php
- Sami/Tests/Parser/NodeVisitorTest.php
- Sami/Tests/Parser/ParserContextTest.php
- Sami/Tests/ProjectTest.php
- Sami/Tests/Reflection/ClassReflectionTest.php
- Sami/Tests/Reflection/MethodReflectionTest.php
- Sami/Tests/Reflection/PropertyReflectionTest.php
- Sami/Tests/TreeTest.php
- composer.json
- composer.lock
I use the `PHPUnit\Framework\TestCase` notation instead of `PHPUnit_Framework_TestCase` while extending our TestCases. This will help us migrate to PHPUnit 6, that [no longer support snake case class names](https://github.com/sebastianbergmann/phpunit/blob/master/ChangeLog-6.0.md#changed-1).
I just need to update `symfony/phpunit-bridge` to support this `namespace`.
> Update to phpunit-bridge 4.0

- Sami/Resources/themes/default/macros.twig
Switches a boolean in the macro to provide, by default, a consistent result on the index page. Fixes #309.
> Inconsistent result on Index Page

- Sami/Parser/NodeVisitor.php
I've started using PHP 7.1 nullable types and noticed, that Sami is not able to parse them. I saw the issue #264, but it does not fix the issue, at least not for parameters.
For example `function setAvatar(?string $data)` will result in a type of `string`, and not `string|null` as expected. The PHP documentation for that element *is* `@param string|null $data`.
This PR fixes this by adding the `null` type to the type array when resolving hints.
> Fix type null for nullable type parameters not added as type

- README.rst
`use Sami\RemoteRepository\GitHubRemoteRepository;` is not used, removed.
> Remove unused 'use'

- Sami/Project.php
thus removing weird `abbr` titles such as `my\namespaced\class\false`
> allow `true` and `false` type-hint

- .travis.yml
To be equal to https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/2.11/.travis.yml#L5-L6 and improve the build times a bit.
> chore: clone last commit

- Sami/Version/GitVersionCollection.php
Hello,
Version 4.1 of Sami is currently not working when using `GitVersionCollection`, because it relies on `Symfony\Component\Process\ProcessBuilder`, which has been removed in version 4 of `symfony/process`.
Version 4.0 of Sami pointed to version `~3.0` of `symfony/process`, so that works regularly. According to the Symfony upgrade guide, instead of relying on `ProcessBuilder`, we just use `Process` directly.
The Phar at `http://get.sensiolabs.org/sami.phar` is affected, so it might be breaking some CI builds (that's how I discovered about this).
> Removed use of ProcessBuilder

- Sami/Project.php
This PR allows the `$this` type hint (use case: return type). This removes the absurd cases of `\MyNamespace\$this` in the documentation.
> Allow $this type hint
